/**
 * Словарь синонимов для нормализации STT-вывода.
 * Применяется первым шагом в normalizeInput() — все варианты
 * ("harita", "vakansia", "vacancy", "tarjima") приводятся к канону.
 *
 * При добавлении: длинные ключи обрабатываются первыми автоматически.
 */

export const SYNONYMS: Record<string, string> = {
  // ─── Карта / Map ───
  "карты": "karta",
  "карте": "karta",
  "карту": "karta",
  "картой": "karta",
  "картами": "karta",
  "карта": "karta",
  "harita": "xarita",
  "xaritta": "xarita",
  "haritani": "xarita",
  "haritada": "xarita",
  "xaritani": "xarita",
  "xaritada": "xarita",
  "maps": "karta",
  "map": "karta",

  // ─── Маршрут / Route ───
  "маршрут": "marshrut",
  "маршрута": "marshrut",
  "маршруту": "marshrut",
  "маршрутом": "marshrut",
  "маршруты": "marshrut",
  "маршруте": "marshrut",
  "как пройти": "marshrut",
  "как доехать": "marshrut",
  "как добраться": "marshrut",
  "как проехать": "marshrut",
  "как дойти": "marshrut",
  "доехать": "marshrut",
  "добраться": "marshrut",
  "навигация": "marshrut",
  "навигатор": "marshrut",
  "навигатору": "marshrut",
  "навигации": "marshrut",
  "навигации до": "marshrut",
  "gps": "marshrut",
  "gps-навигатор": "marshrut",
  "навигация по": "marshrut",
  "проложи маршрут": "marshrut",
  "построй маршрут": "marshrut",
  "построить маршрут": "marshrut",
  "проложить маршрут": "marshrut",
  "проложи путь": "marshrut",
  "веди меня": "marshrut",
  "веди до": "marshrut",
  "покажи дорогу": "marshrut",
  "покажи путь": "marshrut",
  "построить путь": "marshrut",
  "route": "marshrut",
  "route to": "marshrut",
  "navigate to": "marshrut",
  "navigate": "marshrut",
  "directions to": "marshrut",
  "directions": "marshrut",
  "marshrut qur": "marshrut",
  "marshrut qurish": "marshrut",
  "yo'l ko'rsat": "marshrut",
  "yo'l ko'r": "marshrut",
  "yol ko'rsat": "marshrut",
  "qanday borish": "marshrut",
  "qanday yetib borish": "marshrut",
  "qanday boraman": "marshrut",
  "qanday borish mumkin": "marshrut",

  // ─── Работа / Vacancy ───
  "вакансию": "vakansiya",
  "вакансии": "vakansiya",
  "вакансий": "vakansiya",
  "вакансиями": "vakansiya",
  "вакансия": "vakansiya",
  "vakansia": "vakansiya",
  "vacansy": "vakansiya",
  "vacansia": "vakansiya",
  "vacancy": "vakansiya",
  "vacancies": "vakansiya",
  "jobs": "vakansiya",
  "job": "vakansiya",
  "объявления": "vakansiya",
  "объявление": "vakansiya",
  "предложения работы": "vakansiya",
  "предложение работы": "vakansiya",
  "свободные вакансии": "vakansiya",
  "свободных вакансий": "vakansiya",
  "свежие вакансии": "vakansiya",
  "свежих вакансий": "vakansiya",
  "высокооплачиваемая работа": "vakansiya",
  "высокооплачиваемую работу": "vakansiya",
  "высокооплачиваемой работы": "vakansiya",
  "хорошо оплачиваемая работа": "vakansiya",
  "хорошооплачиваемую работу": "vakansiya",
  "работа сварщиком": "vakansiya",
  "работа водителем": "vakansiya",
  "работа строителем": "vakansiya",
  "работа поваром": "vakansiya",
  "работа сварщика": "vakansiya",
  "работа водителя": "vakansiya",
  "работа строителя": "vakansiya",
  "работа повара": "vakansiya",
  "работа с проживанием": "vakansiya",
  "работа с жильем": "vakansiya",
  "работа с питанием": "vakansiya",
  "вахта": "vakansiya",
  "вахтой": "vakansiya",
  "вахту": "vakansiya",
  "вахтовая работа": "vakansiya",
  "вахтовик": "vakansiya",
  "смены": "vakansiya",
  "смена": "vakansiya",
  "смену": "vakansiya",
  "подработка": "vakansiya",
  "подработку": "vakansiya",
  "временная работа": "vakansiya",
  "временную работу": "vakansiya",
  "разовая работа": "vakansiya",
  "ищу работу": "vakansiya",
  "ищу работу сварщиком": "vakansiya",
  "ищу работу водителем": "vakansiya",
  "есть работа": "vakansiya",
  "есть вакансия": "vakansiya",
  "есть вакансии": "vakansiya",
  "нужна работа": "vakansiya",
  "нужны работники": "vakansiya",
  "есть вакансия в": "vakansiya",
  "ищу работу в": "vakansiya",
  "ищу работу рядом": "vakansiya",
  "работа рядом": "vakansiya",
  "работа сегодня": "vakansiya",
  "работа без опыта": "vakansiya",
  "работа сегодня оплата": "vakansiya",
  "rabota": "vakansiya",
  "rabotu": "vakansiya",
  "ish top": "vakansiya",
  "ish qidir": "vakansiya",
  "ish kerak": "vakansiya",
  "vakansiya qidir": "vakansiya",
  "vakansiya top": "vakansiya",
  "topib ber": "vakansiya",
  "qidirib ber": "vakansiya",
  "izlab top": "vakansiya",
  "ishla": "vakansiya",
  "ishlab": "vakansiya",
  "vakansiyalar": "vakansiya",
  "find job": "vakansiya",
  "search job": "vakansiya",
  "search jobs": "vakansiya",
  "find work": "vakansiya",
  "find a job": "vakansiya",

  // ─── Перевод / OCR ───
  "переведи": "tarjima",
  "перевести": "tarjima",
  "перевод": "tarjima",
  "перевожу": "tarjima",
  "переведет": "tarjima",
  "переведу": "tarjima",
  "переведите": "tarjima",
  "распознай": "ocr",
  "распознать": "ocr",
  "распознавание": "ocr",
  "распознавания": "ocr",
  "распознать текст": "ocr",
  "распознавания текста": "ocr",
  "прочитай": "ocr",
  "прочитать": "ocr",
  "прочитайте": "ocr",
  "прочитать документ": "ocr",
  "сканируй": "ocr",
  "сканировать": "ocr",
  "сканирования": "ocr",
  "сканирование": "ocr",
  "скан": "ocr",
  "сканер": "ocr",
  "отсканируй": "ocr",
  "отсканировать": "ocr",
  "translate": "tarjima",
  "translation": "tarjima",
  "scan": "ocr",
  "scanner": "ocr",
  "read": "ocr",
  "read text": "ocr",
  "ocr scan": "ocr",
  "ocr photo": "ocr",
  "tarjima qil": "tarjima",
  "tarjimasi": "tarjima",
  "tarjimalash": "tarjima",
  "tarjima qilish": "tarjima",
  "skanerla": "ocr",
  "skanerlash": "ocr",
  "skaner qil": "ocr",
  "o'qib ber": "ocr",
  "rasmni o'qib ber": "ocr",
  "hujjatni o'qib ber": "ocr",
  "matnni o'qib ber": "ocr",

  // ─── Действия / Actions ───
  "покажи": "ko'rsat",
  "показать": "ko'rsat",
  "покажет": "ko'rsat",
  "покажите": "ko'rsat",
  "show": "ko'rsat",
  "display": "ko'rsat",
  "открой": "och",
  "открыть": "och",
  "open": "och",
  "найди": "ish_top",
  "найти": "ish_top",
  "ищу": "ish_top",
  "искать": "ish_top",
  "искал": "ish_top",
  "поищи": "ish_top",
  "найти адрес": "ish_top",
  "найти место": "ish_top",
  "найти компанию": "ish_top",
  "найти аптеку": "ish_top",
  "найти больницу": "ish_top",
  "найти вокзал": "ish_top",
  "найти аэропорт": "ish_top",
  "find": "ish_top",
  "search": "ish_top",
  "look for": "ish_top",
  "lookup": "ish_top",
  "где": "qayerda",
  "где находится": "qayerda",
  "где есть": "qayerda",
  "где искать": "qayerda",
  "где мне найти": "qayerda",
  "where": "qayerda",
  "where is": "qayerda",
  "ближайший": "eng_yaqin",
  "ближайшая": "eng_yaqin",
  "ближайшее": "eng_yaqin",
  "ближайшего": "eng_yaqin",
  "ближайшую": "eng_yaqin",
  "рядом": "eng_yaqin",
  "недалеко": "eng_yaqin",
  "поблизости": "eng_yaqin",
  "nearest": "eng_yaqin",
  "closest": "eng_yaqin",
  "near": "eng_yaqin",
  "eng yaqin": "eng_yaqin",
  "eng yaqini": "eng_yaqin",

  // ─── Работодатель / Employer ───
  "работодатель": "ish_beruvchi",
  "работодателя": "ish_beruvchi",
  "работодателем": "ish_beruvchi",
  "работодатели": "ish_beruvchi",
  "компания": "kompaniya",
  "компанию": "kompaniya",
  "компании": "kompaniya",
  "компанией": "kompaniya",
  "организация": "tashkilot",
  "организацию": "tashkilot",
  "организации": "tashkilot",
  "организацией": "tashkilot",
  "фирма": "firma",
  "фирму": "firma",
  "фирмы": "firma",
  "фирмой": "firma",
  "предприятие": "tashkilot",
  "предприятия": "tashkilot",
  "предприятию": "tashkilot",
  "мошенник": "mushennik",
  "мошенники": "mushennik",
  "мошенника": "mushennik",
  "мошенникам": "mushennik",
  "мошенничество": "mushennik",
  "мошенничества": "mushennik",
  "обман": "mushennik",
  "обмана": "mushennik",
  "обманывают": "mushennik",
  "доверять": "ishonch",
  "довериться": "ishonch",
  "доверяю": "ishonch",
  "не доверяю": "ishonch",
  "надёжный": "ishonch",
  "надежный": "ishonch",
  "надёжная": "ishonch",
  "надёжного": "ishonch",
  "отзывы": "otziv",
  "отзыв": "otziv",
  "отзывов": "otziv",
  "отзывам": "otziv",
  "отзывы о компании": "otziv",
  "reviews": "otziv",
  "review": "otziv",
  "ish beruvchi": "ish_beruvchi",
  "kompaniya": "kompaniya",
  "firma": "firma",
  "tashkilot": "tashkilot",
  "tekshir": "ish_beruvchi",
  "tekshirish": "ish_beruvchi",
  "aldovchi": "mushennik",
  "aldovchilar": "mushennik",
  "ishonch": "ishonch",
  "ishonchli": "ishonch",
  "ishonchsiz": "ishonch",
  "отзови": "otziv",
  "отзывами": "otziv",
  "отзывах": "otziv",
  "company": "kompaniya",
  "employer": "ish_beruvchi",
  "verify": "tekshirish",
  "verify company": "ish_beruvchi",
  "verify employer": "ish_beruvchi",
  "check employer": "ish_beruvchi",

  // ─── Документы / Documents ───
  "документ": "hujjat",
  "документа": "hujjat",
  "документе": "hujjat",
  "документы": "hujjat",
  "документов": "hujjat",
  "документом": "hujjat",
  "документы проверить": "hujjat_tekshirish",
  "проверить документы": "hujjat_tekshirish",
  "проверить регистрацию": "hujjat_tekshirish",
  "проверить патент": "hujjat_tekshirish",
  "проверить паспорт": "hujjat_tekshirish",
  "проверить миграционную карту": "hujjat_tekshirish",
  "продлить регистрацию": "hujjat_tekshirish",
  "продлить патент": "hujjat_tekshirish",
  "когда заканчивается регистрация": "hujjat_tekshirish",
  "когда платить патент": "hujjat_tekshirish",
  "когда заканчивается патент": "hujjat_tekshirish",
  "когда оплачивать патент": "hujjat_tekshirish",
  "hujjat": "hujjat",
  "hujjatni": "hujjat",
  "hujjatlar": "hujjat",
  "hujjatlarni": "hujjat",
  "pasport": "pasport",
  "паспорт": "pasport",
  "паспорта": "pasport",
  "паспорту": "pasport",
  "паспортом": "pasport",
  "патенте": "patent",
  "патента": "patent",
  "патенту": "patent",
  "патентом": "patent",
  "патенты": "patent",
  "патентов": "patent",
  "миграционная карта": "migratsion_karta",
  "миграционной карты": "migratsion_karta",
  "миграционную карту": "migratsion_karta",
  "миграционке": "migratsion_karta",
  "регистрация": "registratsiya",
  "регистрацию": "registratsiya",
  "регистрации": "registratsiya",
  "регистрацией": "registratsiya",
  "registratsiya": "registratsiya",
  "patent": "patent",
  "migratsion_karta": "migratsion_karta",

  // ─── Фото / Image ───
  "фото": "rasm",
  "фотография": "rasm",
  "фотографию": "rasm",
  "фотографии": "rasm",
  "фотографий": "rasm",
  "фотографией": "rasm",
  "картинка": "rasm",
  "картинку": "rasm",
  "картинки": "rasm",
  "изображение": "rasm",
  "изображения": "rasm",
  "изображений": "rasm",
  "изображению": "rasm",
  "фотку": "rasm",
  "фоток": "rasm",
  "rasm": "rasm",
  "rasmni": "rasm",
  "rasmdan": "rasm",
  "rasmga": "rasm",
  "rasmda": "rasm",
  "rasmlar": "rasm",
  "rasmlarni": "rasm",
  "photo": "rasm",
  "image": "rasm",
  "picture": "rasm",

  // ─── Текст / Text ───
  "текст": "matn",
  "текста": "matn",
  "тексту": "matn",
  "текстом": "matn",
  "matn": "matn",
  "matnni": "matn",
  "matnlar": "matn",
  "text": "matn",

  // ─── Бумага / Paper ───
  "бумага": "hujjat",
  "бумаги": "hujjat",
  "бумагу": "hujjat",
  "бумажку": "hujjat",
  "бумажки": "hujjat",
  "бумажек": "hujjat",

  // ─── Адрес / Address ───
  "адрес": "manzil",
  "адреса": "manzil",
  "адресу": "manzil",
  "адресом": "manzil",
  "локация": "manzil",
  "локацию": "manzil",
  "локации": "manzil",
  "место": "manzil",
  "места": "manzil",
  "месту": "manzil",
  "местом": "manzil",
  "manzil": "manzil",
  "manzili": "manzil",
  "manzilni": "manzil",
  "manzillar": "manzil",
  "manzillarni": "manzil",
  "address": "manzil",
  "location": "manzil",
  "place": "manzil",
  "spot": "manzil",

  // ─── AI команды ───
  "объясни": "tushuntir",
  "объясните": "tushuntir",
  "объяснить": "tushuntir",
  "помоги": "yordam",
  "помогите": "yordam",
  "помочь": "yordam",
  "помощь": "yordam",
  "расскажи": "aytib_ber",
  "расскажите": "aytib_ber",
  "рассказать": "aytib_ber",
  "что делать": "nima_qilish",
  "что мне делать": "nima_qilish",
  "что надо делать": "nima_qilish",
  "что означает": "nima_qilish",
  "что значит": "nima_qilish",
  "как оформить": "qanday_rasmiylashtirish",
  "как получить": "qanday_olish",
  "как перевести": "qanday_tarjima",
  "как найти": "qanday_topish",
  "как сделать": "qanday_qilish",
  "как оплатить": "qanday_tolov",
  "как оформить патент": "qanday_rasmiylashtirish",
  "как получить патент": "qanday_olish",
  "tushuntir": "tushuntir",
  "tushuntirib ber": "tushuntir",
  "yordam": "yordam",
  "yordam ber": "yordam",
  "yordamchi": "yordam",
  "yordam qil": "yordam",
  "aytib ber": "aytib_ber",
  "nima qilish": "nima_qilish",
  "nima qilaman": "nima_qilish",
  "nima qilay": "nima_qilish",
  "qanday qilish": "qanday_qilish",
  "explain": "tushuntir",
  "help": "yordam",
  "help me": "yordam",
  "tell me": "aytib_ber",
  "what to do": "nima_qilish",
  "how to": "qanday_qilish",
  "how do i": "qanday_qilish",

  // ─── SOS / Экстренные ситуации ───
  "полиция": "politsiya",
  "полицию": "politsiya",
  "полиции": "politsiya",
  "полицейский": "politsiya",
  "полицейские": "politsiya",
  "полицейского": "politsiya",
  "проверка": "tekshirish",
  "проверки": "tekshirish",
  "проверку": "tekshirish",
  "проверкой": "tekshirish",
  "остановили": "to'xtatdi",
  "остановила": "to'xtatdi",
  "остановят": "to'xtatdi",
  "задержали": "qamoq",
  "задержан": "qamoq",
  "задержание": "qamoq",
  "задержать": "qamoq",
  "украли": "o'g'irladi",
  "украли документы": "o'g'irladi",
  "потерял": "yo'qotdi",
  "потеряла": "yo'qotdi",
  "потерял паспорт": "yo'qotdi",
  "потерял документы": "yo'qotdi",
  "потерял права": "yo'qotdi",
  "экстренная помощь": "sos",
  "экстренной помощи": "sos",
  "экстренную помощь": "sos",
  "экстренные службы": "sos",
  "экстренных служб": "sos",
  "срочная помощь": "sos",
  "срочной помощи": "sos",
  "нужен адвокат": "sos",
  "нужна помощь юриста": "sos",
  "нужна юридическая помощь": "sos",
  "нужна юридическая": "sos",
  "юридическая помощь": "sos",
  "юридической помощи": "sos",
  "юридическую помощь": "sos",
  "sos": "sos",
  "помощь срочно": "sos",
  "экстренно": "sos",
  "полицейская проверка": "sos",
  "politsiya": "politsiya",
  "to'xtatdi": "to'xtatdi",
  "to'xtatib qol": "to'xtatdi",
  "qamoq": "qamoq",
  "qamoqqa": "qamoq",
  "o'g'irladi": "o'g'irladi",
  "o'g'irlab": "o'g'irladi",
  "o'g'irlangan": "o'g'irladi",
  "yo'qotdi": "yo'qotdi",
  "yo'qotib": "yo'qotdi",
  "yo'qotilgan": "yo'qotdi",
  "police": "politsiya",
  "stopped": "to'xtatdi",
  "detained": "qamoq",
  "arrested": "qamoq",
  "stolen": "o'g'irladi",
  "lost passport": "yo'qotdi",
  "lost documents": "yo'qotdi",
  "emergency": "sos",
  "lawyer": "sos",

  // ─── Ближайший объект ───
  "ближайший магазин": "eng_yaqin_magazin",
  "ближайшая аптека": "eng_yaqin_apteka",
  "ближайшая больница": "eng_yaqin_kasalxona",
  "ближайший вокзал": "eng_yaqin_vokzal",
  "ближайший аэропорт": "eng_yaqin_aeroport",
  "ближайшая мечеть": "eng_yaqin_masjid",
  "ближайший банк": "eng_yaqin_bank",
  "ближайший мфц": "eng_yaqin_mfc",
  "ближайший метро": "eng_yaqin_metro",
  "eng yaqin magazin": "eng_yaqin_magazin",
  "eng yaqin apteka": "eng_yaqin_apteka",
  "eng yaqin shifoxona": "eng_yaqin_kasalxona",
  "eng yaqin kasalxona": "eng_yaqin_kasalxona",
  "eng yaqin vokzal": "eng_yaqin_vokzal",
  "eng yaqin aeroport": "eng_yaqin_aeroport",
  "eng yaqin masjid": "eng_yaqin_masjid",
  "eng yaqin bank": "eng_yaqin_bank",
  "eng yaqin mfc": "eng_yaqin_mfc",
  "eng yaqin metro": "eng_yaqin_metro",
  "nearest store": "eng_yaqin_magazin",
  "nearest pharmacy": "eng_yaqin_apteka",
  "nearest hospital": "eng_yaqin_kasalxona",
  "nearest station": "eng_yaqin_vokzal",
  "nearest airport": "eng_yaqin_aeroport",
  "nearest mosque": "eng_yaqin_masjid",
  "nearest bank": "eng_yaqin_bank",
  "nearest subway": "eng_yaqin_metro",

  // ─── Сегодня / Сейчас ───
  "сегодня": "bugun",
  "сегодняшний": "bugun",
  "сейчас": "hozir",
  "прямо сейчас": "hozir",
  "срочно": "tezkor",
  "быстро": "tezkor",
  "немедленно": "tezkor",
  "бугун": "bugun",
  "bugun": "bugun",
  "hozir": "hozir",
  "hozircha": "hozir",
  "tezkor": "tezkor",
  "tezda": "tezkor",
  "today": "bugun",
  "now": "hozir",
  "urgent": "tezkor",

  // ─── Вежливые модификаторы ───
  "пожалуйста": "iltimos",
  "пж": "iltimos",
  "плиз": "iltimos",
  "будь добр": "iltimos",
  "будьте добры": "iltimos",
  "iltimos": "iltimos",
  "menga": "menga",
  "мне": "menga",
  "для меня": "menga",
  "please": "iltimos",
  "pls": "iltimos",

  // ─── Премиум / Подписка ───
  "премиум": "premium",
  "premium": "premium",
  "подписка": "obuna",
  "подписку": "obuna",
  "подписки": "obuna",
  "оформить подписку": "obuna",
  "оформить premium": "premium",
  "купить премиум": "premium",
  "купить premium": "premium",
  "подключить premium": "premium",
  "подключить премиум": "premium",
  "obuna": "obuna",
  "obuna bo'lish": "obuna",
  "obuna olish": "obuna",
  "subscription": "obuna",

  // ─── Общие глаголы ───
  "открывать": "och",
  "открыт": "och",
  "закрыть": "yop",
  "закрывать": "yop",
  "перейти": "o'tish",
  "перейти к": "o'tish",
  "перейди": "o'tish",
  "переходи": "o'tish",
  "вернуться": "qaytish",
  "вернись": "qaytish",
  "вернусь": "qaytish",
  "сохранить": "saqlash",
  "сохрани": "saqlash",
  "сохранение": "saqlash",
  "сохранил": "saqlash",
  "удали": "o'chirish",
  "удаление": "o'chirish",
  "отправить": "yuborish",
  "отправь": "yuborish",
  "отправка": "yuborish",
  "отправлено": "yuborish",
  "поделиться": "ulashish",
  "поделись": "ulashish",
  "скопировать": "nusxalash",
  "скопируй": "nusxalash",
  "копировать": "nusxalash",

  // ─── Общие существительные ───
  "страница": "sahifa",
  "страницу": "sahifa",
  "страницы": "sahifa",
  "раздел": "bo'lim",
  "раздела": "bo'lim",
  "разделу": "bo'lim",
  "разделы": "bo'lim",
  "настройки": "sozlamalar",
  "настройка": "sozlama",
  "настройку": "sozlama",
  "настройке": "sozlama",
  "профиль": "profil",
  "профиля": "profil",
  "профилю": "profil",
  "профилем": "profil",
  "кабинет": "kabinet",
  "кабинета": "kabinet",
  "кабинету": "kabinet",
  "кабинетом": "kabinet",
  "главная": "bosh",
  "главную": "bosh",
  "главной": "bosh",
  "история": "tarix",
  "истории": "tarix",
  "историю": "tarix",
  "избранное": "sevimli",
  "избранного": "sevimli",
  "избранные": "sevimli",
  "закладка": "xatcho'plar",
  "закладок": "xatcho'plar",
  "sahifa": "sahifa",
  "sahifani": "sahifa",
  "bo'lim": "bo'lim",
  "bo'limi": "bo'lim",
  "sozlamalar": "sozlamalar",
  "profil": "profil",
  "kabinet": "kabinet",
  "bosh": "bosh",
  "bosh sahifa": "bosh",
  "tarix": "tarix",
  "sevimli": "sevimli",
};